export let galleryData = [
  {slug: "canadiens", src: "/images/canadiens.svg", heading: "Montreal Canadiens", description: "The Montreal Canadiens are a historic NHL team, founded in 1909.", alt: "nhl team logo image", extendedInfo: `The Montreal Canadiens are one of the oldest and most successful professional ice hockey teams in the world. Founded in 1909, they are based in Montreal, Quebec, Canada. The team is a member of the Atlantic Division in the Eastern Conference of the National Hockey League (NHL).
  The Canadiens have a rich and storied history, boasting an impressive record of 24 Stanley Cup championships, the most in NHL history. Their dominance in the early years of the league earned them the nickname "The Flying Frenchmen." The team's success can be attributed to legendary players, strategic coaching, and a passionate fan base.
  In the 1940s and 1950s, the Canadiens were led by the iconic Maurice "Rocket" Richard, who became the first player in NHL history to score 50 goals in a single season in 1944-45. The 1960s were marked by the emergence of other legends like Jean Beliveau and Henri Richard, contributing to more Stanley Cup victories.
  Perhaps the most celebrated era for the Canadiens was the late 1970s when they were led by coach Scotty Bowman and featured star players like Guy Lafleur, Ken Dryden, and Larry Robinson. The team won four consecutive Stanley Cups from 1976 to 1979, solidifying their status as a hockey dynasty.
  Throughout their history, the Canadiens have produced numerous Hall of Fame players and have maintained a reputation for excellence. The team's jersey, adorned with the iconic red, white, and blue colors and the historic CH logo, is recognized worldwide.
  As for specific records, the Canadiens hold the record for the most NHL regular-season championships with 24 and have accumulated numerous individual records by their players over the years. It's essential to check the latest statistics and records as they can change with each season.
  The Montreal Canadiens continue to be a powerhouse in the NHL, and their legacy as one of the most successful and iconic hockey franchises in the world is firmly established`, gradient1: "from-red-800", gradient2: "to-white", cups: "24"},

  {slug: "canucks", src: "/images/canucks.svg", heading: "Vancouver Canucks", description: "he Vancouver Canucks, established in 1970, bring a Pacific flair to the NHL.", alt: "nhl team logo image", extendedInfo: `The Vancouver Canucks, founded in 1970, are a professional ice hockey team based in Vancouver, British Columbia, Canada. They compete in the Pacific Division of the Western Conference in the National Hockey League (NHL).
  The Canucks' early years were marked by struggles and a gradual building process. In the 1980s, the team experienced success with players like Stan Smyl, Trevor Linden, and Pavel Bure. The 1994 season stands out as a historic one for the Canucks when they reached the Stanley Cup Finals for the first time in franchise history. Despite falling short against the New York Rangers, the run captured the hearts of Vancouver fans.
  The early 2000s saw the emergence of the West Coast Express line, featuring Markus Naslund, Todd Bertuzzi, and Brendan Morrison, bringing excitement to Canucks' hockey. However, they faced playoff disappointments.
  The late 2000s and early 2010s marked a significant turning point for the Canucks. Led by the Sedin twins, Henrik and Daniel, the team experienced sustained success. In 2011, they had a remarkable season, winning the Presidents' Trophy for the best regular-season record and reaching the Stanley Cup Finals for the second time in franchise history. Unfortunately, they faced another heartbreak, losing to the Boston Bruins in a hard-fought seven-game series.
  Despite not capturing a Stanley Cup, the Canucks have had notable players and moments throughout their history. Pavel Bure, known as the "Russian Rocket," is one of the most electrifying players in franchise history, and his number 10 jersey has been retired by the team.
  In recent years, the Canucks continue to strive for success, with a mix of young talent and experienced players. Bo Horvat and Elias Pettersson are among the current stars leading the team.
  While the Canucks may not have the extensive history and championship record of some other franchises, they remain a beloved and competitive team in the NHL, with a passionate fan base supporting them through thick and thin.`, gradient1: "from-sky-950", gradient2: "to-slate-300", cups: "0"},

  {slug: "flames", src: "/images/flames.svg", heading: "Calgary Flames", description: "The Calgary Flames, established in 1972, are an NHL team known for their fiery spirit.", alt: "nhl team logo image", extendedInfo: `The Calgary Flames, founded in 1972, are a professional ice hockey team based in Calgary, Alberta, Canada. They compete in the Pacific Division of the Western Conference in the National Hockey League (NHL).
  The Flames' early years were marked by immediate success, as they reached the playoffs in six of their first eight seasons. In 1986, the Flames advanced to the Stanley Cup Finals for the first time in franchise history but were defeated by the Montreal Canadiens in a thrilling five-game series.
  One of the most iconic moments in Flames' history came in 1989 when they won their first and only Stanley Cup. Led by stars like Lanny McDonald, Doug Gilmour, and goaltender Mike Vernon, the Flames defeated the Montreal Canadiens in six games to capture the championship. McDonald's famous mustache and the celebratory image of him lifting the Cup remain etched in hockey lore.
  The Flames have had their share of legendary players, including Jarome Iginla, who became the franchise's all-time leading scorer and one of the most respected players in the league during his tenure.
  The team has faced various challenges and rebuilding phases, but in recent years, the Flames have been competitive in the NHL. The emergence of young talent, coupled with experienced players, has kept the team in playoff contention.
  The Scotiabank Saddledome serves as the Flames' home arena, and their team colors of red, yellow, and white are prominently featured in their jerseys. The Flames have a dedicated fan base known for its passionate support, especially during the "C of Red" playoff traditions.
  While the Flames may not have multiple championships, their history is marked by memorable moments, iconic players, and a commitment to success. The team continues to strive for excellence and aims to add more chapters to its storied history in the NHL.`, gradient1: "from-red-700", gradient2: "to-yellow-500", cups: "1"},

  {slug: "jets", src: "/images/jets.svg", heading: "Winnipeg Jets", description: "The Winnipeg Jets, reborn in 2011, bring NHL excitement to the heart of Canada.", alt: "nhl team logo image", extendedInfo: `The Winnipeg Jets, founded in 1999, are a professional ice hockey team based in Winnipeg, Manitoba, Canada. They compete in the Central Division of the Western Conference in the National Hockey League (NHL).
  The Jets' history can be traced back to the original Winnipeg Jets, who were part of the World Hockey Association (WHA) in the 1970s. The WHA Jets had considerable success, winning three championships before the WHA-NHL merger in 1979. The team then joined the NHL, but financial challenges led to their relocation to Arizona in 1996, becoming the Phoenix Coyotes.
  The current incarnation of the Winnipeg Jets was established in 2011 when the Atlanta Thrashers relocated to Winnipeg. The return of the Jets was met with immense enthusiasm from the city and its passionate hockey fans.
  Since their return, the Jets have become a competitive force in the NHL. The team has been led by standout players like Blake Wheeler, Mark Scheifele, and goaltender Connor Hellebuyck. In the 2017-2018 season, the Jets reached the Western Conference Finals, marking a significant achievement for the franchise.
  The Jets' team colors of navy blue, light blue, and white are reflected in their jerseys, and the Bell MTS Place serves as their home arena. The fans, known for their "Winnipeg Whiteout" tradition during the playoffs, create a vibrant and electric atmosphere in support of their team.
  While the current Jets have not yet secured a Stanley Cup championship, they continue to build a competitive roster and aim for success in the NHL. The return of NHL hockey to Winnipeg has rejuvenated the city's love for the sport, and the Jets remain a source of pride for their dedicated fan base.`, gradient1: "from-blue-900", gradient2: "to-slate-400", cups: "0"},

  {slug: "leafs", src: "/images/leafs.svg", heading: "Toronto Maple Leafs", description: "The Toronto Maple Leafs, dating back to 1917, stand as an enduring force in the NHL.", alt: "nhl team logo image", extendedInfo: `The Toronto Maple Leafs, founded in 1917, are one of the "Original Six" teams in the National Hockey League (NHL) and are based in Toronto, Ontario, Canada. The team competes in the Atlantic Division of the Eastern Conference.
  The Maple Leafs have a storied history and are one of the most iconic and popular teams in the NHL. The franchise has undergone various phases of success and rebuilding throughout its history.
  In the early years, the Leafs were dominant, winning multiple Stanley Cups in the 1940s. The team featured legends like "The Kid" Line (Joe Primeau, Charlie Conacher, and Busher Jackson) and later added icons like Syl Apps and Turk Broda.
  The 1960s saw the Leafs add more championships to their resume, with players like Dave Keon, George Armstrong, and Johnny Bower contributing to their success. However, the following decades brought challenges, and the team underwent rebuilding phases.
  In the 1990s and early 2000s, the Leafs experienced a resurgence with players like Doug Gilmour, Mats Sundin, and Curtis Joseph. Despite competitive teams, the Leafs fell short of capturing a Stanley Cup during this period.
  The current era is marked by a talented roster led by stars like Auston Matthews, Mitch Marner, and John Tavares. The team plays its home games at the Scotiabank Arena, and their iconic blue and white jerseys are instantly recognizable.
  The Maple Leafs have a massive and passionate fan base, and their games are a focal point in the hockey-crazed city of Toronto. The quest for the Stanley Cup continues to be a central narrative for the team, with fans eagerly awaiting the next championship.
  While the Leafs haven't secured a Stanley Cup since 1967, the team's rich history, legendary players, and passionate fan support make them a perennial contender and a symbol of Canadian hockey tradition.`, gradient1: "from-blue-800", gradient2: "to-white", cups: "13"},

  {slug: "oilers", src: "/images/oilers.svg", heading: "Edmonton Oilers", description: "The Edmonton Oilers, founded in 1971, known for hockey greatness.", alt: "nhl team logo image", extendedInfo: `The Edmonton Oilers, founded in 1971, are a professional ice hockey team based in Edmonton, Alberta, Canada. They compete in the Pacific Division of the Western Conference in the National Hockey League (NHL).
  The Oilers have a storied history that is closely tied to their success in the 1980s, known as the "Dynasty Years." Led by legendary players Wayne Gretzky, Mark Messier, Jari Kurri, Paul Coffey, and Grant Fuhr, the team dominated the NHL, winning five Stanley Cups in a seven-year span from 1984 to 1990. Wayne Gretzky, often regarded as the greatest hockey player of all time, set numerous records while playing for the Oilers.
  The team's success in the 1980s solidified their place in hockey history, and the Oilers became synonymous with high-scoring, fast-paced play. The dynasty years created a legacy that is still celebrated by fans in Edmonton and remembered as one of the most remarkable periods in NHL history.
  In the years following the dynasty, the Oilers went through periods of rebuilding and transition. The team has seen talented players like Connor McDavid and Leon Draisaitl emerge as stars, bringing new hope and excitement to the fan base.
  The Oilers play their home games at Rogers Place, and their team colors of orange, blue, and white are prominently featured in their jerseys. The fan base is known for its passionate support, and the Oilers' games are a significant event in the city.
  While the Oilers have not replicated the championship success of the 1980s, they remain a team with a rich history, a commitment to excellence, and a dedicated fan following. The presence of superstars like McDavid and Draisaitl ensures that the Oilers continue to be a competitive force in the NHL, with aspirations of adding more championships to their storied legacy.`, gradient1: "from-orange-600", gradient2: "to-blue-900", cups: "5"},

  {slug: "sabres", src: "/images/sabres.svg", heading: "Buffalo Sabres", description: "The Buffalo Sabres, founded in 1970, represent hockey pride in Buffalo, New York.", alt: "nhl team logo image", extendedInfo: `The Buffalo Sabres, established in 1970, are a professional ice hockey team based in Buffalo, New York. They compete in the Atlantic Division of the Eastern Conference in the National Hockey League (NHL). The team's name pays homage to the North American buffalo, a symbol of the western frontier, and the saber, a historic weapon associated with military prowess.
  The early years of the Sabres were marked by immediate success, as the team made the playoffs in each of its first three seasons. In the 1974-75 season, led by head coach Joe Crozier and players like Gilbert Perreault, Rick Martin, and Rene Robert, the Sabres reached the Stanley Cup Finals, ultimately falling to the Philadelphia Flyers.
  The late 1970s and early 1980s saw the Sabres continue to be a competitive force in the league. Perreault, who spent his entire career with the Sabres, became the franchise's all-time leading scorer and a beloved figure in Buffalo sports history.
  The 1990s brought another era of success for the Sabres, featuring stars like Pat LaFontaine, Alexander Mogilny, and Dominik Hasek. In the 1998-99 season, the team reached the Stanley Cup Finals for the second time in franchise history but fell short to the Dallas Stars in a hard-fought six-game series.
  In recent years, the Sabres have faced challenges and rebuilding phases, striving to regain their competitive edge. The team has seen the emergence of young talent, including Jack Eichel and Rasmus Dahlin, offering hope for the future.
  The Sabres play their home games at the KeyBank Center, and their team colors of blue, gold, and white are featured in their jerseys. The passionate fan base, known as the "Sabres Mafia," continues to support the team through highs and lows, creating a unique and spirited atmosphere at games.
  While the Sabres have yet to capture a Stanley Cup, their history is marked by memorable moments, iconic players, and a dedicated fan base. As the team continues its journey, Buffalo fans remain hopeful for future success and the realization of championship aspirations.`, gradient1: "from-blue-900", gradient2: "to-yellow-500", cups: "0"},

  {slug: "senators", src: "/images/senators.svg", heading: "Ottawa Senators", description: "The Ottawa Senators, founded in 1992, represent Canada's capital in the NHL.", alt: "nhl team logo image", extendedInfo: `The Ottawa Senators, founded in 1992, are a professional ice hockey team based in Ottawa, Ontario, Canada. They compete in the Atlantic Division of the Eastern Conference in the National Hockey League (NHL). The team's name pays homage to the original Ottawa Senators, who played in the NHL from 1917 to 1934.
  The modern Senators entered the league as an expansion team, and their early years were marked by building a competitive roster. In the 1996-97 season, only their fifth year of existence, the Senators made an impressive playoff run, reaching the second round. This early success set the tone for the team's aspirations in the NHL.
  The late 1990s and early 2000s saw the Senators become a perennial playoff contender. Key players during this era included Daniel Alfredsson, Marian Hossa, and Zdeno Chara. In the 2006-07 season, the Senators reached the Stanley Cup Finals but were defeated by the Anaheim Ducks in a hard-fought five-game series.
  Daniel Alfredsson, the longtime captain and face of the franchise, became one of the greatest players in Senators history. The "Alfie" era was marked by leadership, skill, and a deep connection with the Ottawa community.
  In recent years, the Senators have undergone a rebuilding phase, focusing on developing young talent. Players like Erik Karlsson, Mark Stone, and Thomas Chabot have emerged as key contributors, providing hope for the future.
  The Senators play their home games at the Canadian Tire Centre, and their team colors of red, black, and white are featured in their jerseys. The fan base, known for its passionate support, has weathered the ups and downs of the team's journey.
  While the Senators have not captured a Stanley Cup, their history is defined by moments of resilience, talented players, and a commitment to success. As the team continues its development and aims for future glory, Ottawa fans remain dedicated to supporting their beloved Senators.`, gradient1: "from-yellow-700", gradient2: "to-white", cups: "0"},

  {slug: "redwings", src: "/images/wings.svg", heading: "Detroit Redwings", description: "The Detroit Red Wings, founded in 1926, they have 11 Stanley Cup victories.", alt: "nhl team logo image", extendedInfo: `The Detroit Red Wings, founded in 1926, are one of the "Original Six" teams in the National Hockey League (NHL) and are based in Detroit, Michigan. The team competes in the Atlantic Division of the Eastern Conference.
  The Red Wings have a storied and illustrious history, characterized by success, iconic players, and a commitment to excellence. The franchise enjoyed its first taste of success in the 1930s, winning multiple Stanley Cups with legendary players like Larry Aurie and Marty Barry.
  The 1950s marked another period of dominance for the Red Wings, with stars like Gordie Howe, Ted Lindsay, and Terry Sawchuk leading the way. The team captured four Stanley Cups in six seasons, solidifying its place as a hockey powerhouse.
  The "Dead Wings" era in the 1970s saw a decline in the team's fortunes, but the Red Wings experienced a remarkable turnaround in the 1980s and 1990s. The acquisition of key players like Steve Yzerman, Nicklas Lidstrom, and Sergei Fedorov, coupled with the coaching prowess of Scotty Bowman, propelled the Red Wings to three Stanley Cup championships in six seasons (1997, 1998, and 2002).
  The Red Wings' success continued into the 2000s, making the playoffs for a remarkable 25 consecutive seasons from 1991 to 2016. The team's commitment to drafting and developing talent was evident in the contributions of players like Pavel Datsyuk and Henrik Zetterberg.
  The Red Wings' home games are played at the Little Caesars Arena, and their distinctive red and white jerseys are iconic in the hockey world. The octopus tradition, where fans throw octopuses onto the ice during playoff games, is a unique and cherished aspect of Red Wings' culture.
  While the team has faced challenges in recent years, the Red Wings remain a symbol of excellence in the NHL. The organization's rich history, commitment to success, and passionate fan base ensure that the Detroit Red Wings continue to hold a special place in the hearts of hockey fans worldwide.`, gradient1: "from-red-500", gradient2: "to-white", cups: "11"}
]
